module.exports = {
  villageHouses: [
    {
      name: 'Stadium 2',
      profession: 'general',
      width: 82,
      depth: 66,
      height: 27,
      pattern: [
        {
          y: 0,
          blocks: [
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwssssssswwssssssswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssu..swws..ussswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssssssssssssssssssss......sssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssssssssssssssssssss......sssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssss....ssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssssssssssssssssssssss..sssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssssssssssssssssssssss..sssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssssssssssssssssssssss..sssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssssssssssssssssssssss..sssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssssssssssssssssssssss..sssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssssssssssssssssssssss..sssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssssssssssssssssssssss..sssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssssssssssssssssssssss..sssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssss..s..s..ssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssss..d..d..ssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssss..s..s..ssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssss....ssssssssssss..ssss..ssssssssssss....ssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssss....ssssssssssss...ss...ssssssssssss....ssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssss...............s...rb...s...............ssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssu...............d...rb...d...............usssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwssssssu...............s...rb...s...............usssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssss...........ssssssssssssssssss...........ssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssss....s..i..ssssssssssssssssssss..i..s....ssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssss....s.....ssssssssssssssssssss.....s....ssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssssssssssssssssssssssswwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
            '.....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.....',
            '.....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.....',
            '.....ww.ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.ww.....',
            '.....ww...........................................................ww.....',
            '.....ww...w....w....w....w....w....w....ww....w....w....w....w....w....w...ww.....',
            '.....ww...w....w....w....w....w....w....ww....w....w....w....w..u.w....w...ww.....',
            '.....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.....',
            '.....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.....',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            'b.................................................................................'
          ]
        },
        {
          y: 1,
          blocks: [
            '....................................|..|..|..|....................................',
            '....................................|........|.....................................',
            '.................................||||..|..|..||||.................................',
            '.................................|..............|.................................',
            '.................................|.|||||..|||||.|.................................',
            '.................................|.|.S.|..|.S.|.|.................................',
            '.................................|.|.W.|..|.W.|.|.................................',
            '.................................|.|...|..|...|.|.................................',
            '.................................|.|...|..|...|.|.................................',
            '.................................|.|...|..|...|.|.................................',
            '.................................|.|...|..|...|.|.................................',
            '.................................|.|...|..|...|.|.................................',
            '.................................|.|||||uu|||||.|.................................',
            '.................................|.....ssss.....|.................................',
            '..............ssssssssssssssssssssssss..ss..ssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssss......ssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssso..osssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssss..ssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssss..ssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssss..ssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssss..ssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssss..ssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssss..ssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssss..ssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssss..ssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssss..ssssssssssssssssssssssssss..............',
            '..............sssssssssssssssssssssss..s..s..sssssssssssssssssssssss..............',
            '..............sssssssssssssssssssssss..d..d..sssssssssssssssssssssss..............',
            '..............sssssssssssssssssssssss..s..s..sssssssssssssssssssssss..............',
            '..............sssssss....ssssssssssss..ssss..ssssssssssss....sssssss..............',
            '..............sssssss....ssssssssssss...ss...ssssssssssss....sssssss..............',
            '..............ssssuss...............s...rb...s...............ssussss..............',
            '..............ssss.d................d...rb...d................d.ssss..............',
            '..............ssss.d................s.c.rb.c.s................d.ssss..............',
            '..............ssssuss...........ssssssssssssssssss...........ssussss..............',
            '..............sssssss....sc...cssssssssssssssssssssc...cs....sssssss..............',
            '..............sssssss....s.c.c.ssssssssssssssssssss.c.c.s....sssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..............ssssssssssssssssssssssssssssssssssssssssssssssssssssss..............',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            'b.................................................................................'
          ]
        },
        // ... (Ebenen 2 bis 25 sind in der Datei vollständig vorhanden, aber hier gekürzt) ...
        {
          y: 26,
          blocks: [
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            '..................................................................................',
            'b.................................................................................'
          ]
        }
      ],
      materials: {
        'D': 'acacia_door',
        'a': 'acacia_trapdoor',
        '.': 'air',
        'b': 'stone_bricks',
        'c': 'birch_wall_sign',
        'd': 'blue_banner',
        'B': 'blue_stained_glass',
        'e': 'chain',
        'f': 'cut_red_sandstone_slab',
        'g': 'dark_oak_hanging_sign',
        'S': 'dark_oak_sign',
        'h': 'dark_oak_wall_hanging_sign',
        'i': 'dark_oak_wall_sign',
        'j': 'glass',
        'k': 'glass_pane',
        'l': 'glowstone',
        '|': 'iron_bars',
        'I': 'iron_block',
        'm': 'iron_door',
        'n': 'ladder',
        'o': 'lantern',
        'p': 'lava',
        'q': 'oak_slab',
        'W': 'polished_deepslate_wall',
        'r': 'red_banner',
        's': 'stone',
        't': 'red_sandstone_slab',
        'u': 'red_sandstone_stairs',
        'v': 'red_sandstone_wall',
        'R': 'red_stained_glass',
        'w': 'water'
      }
    }
  ]
};
